apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: prod-
namespace: prod
commonLabels:
  environment: production
patchesStrategicMerge:
  - config.yaml
images:
  - name: ghcr.io/stratpoint-engineering/demo-nodejs-gitops
    newName: ghcr.io/stratpoint-engineering/demo-nodejs-gitops
    newTag: latest # Will be updated by GitHub Actions
