# overlays/staging/config.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: express-app
        env:
        - name: NODE_ENV
          value: staging
        - name: LOG_LEVEL
          value: debug
