apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: staging-
namespace: staging
commonLabels:
  environment: staging
patchesStrategicMerge:
- config.yaml
images:
- name: ghcr.io/your-org/express-app
  newName: ghcr.io/your-org/express-app
  newTag: latest  # Will be updated by GitHub Actions
