# overlays/staging/config.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nodejs-gitops
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: demo-nodejs-gitops
          env:
            - name: NODE_ENV
              value: staging
            - name: LOG_LEVEL
              value: debug
